# Generated by Django 5.0.1 on 2024-01-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('name', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
