# Generated by Django 5.0.1 on 2024-01-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraperApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='name',
            new_name='stringname',
        ),
    ]
