# Generated by Django 5.0.1 on 2024-01-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraperApp', '0002_rename_name_links_stringname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='stringname',
            new_name='name',
        ),
    ]
